version: "3.8"

services:
    telegraf:
      container_name: telegraf
      restart: unless-stopped
      image: telegraf:1.20.3
      ports:
        - "8092:8092"
      environment:
        HOST_PROC: /host/proc
        INFLUXDB_TELEGRAF_HOST: ${INFLUXDB_TELEGRAF_HOST}
      privileged: true
      volumes:
        - /proc:/host/proc:ro
        - ./docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
        - /var/run/docker.sock:/var/run/docker.sock

    influxdb:
      container_name: influxdb
      restart: unless-stopped
      image: influxdb:1.8
      ports:
        - "8086:8086"
      environment:
        INFLUXDB_USER: ${INFLUXDB_USERNAME}
        INFLUXDB_USER_PASSWORD: ${INFLUXDB_PASSWORD}
        INFLUXDB_DB: ${INFLUXDB_DATABASE}
      volumes:
        - ./docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
        - influxdb-data:/var/lib/influxdb
        
    grafana:
      container_name: grafana
      restart: unless-stopped
      image: grafana/grafana:8.2.1
      user: "root"
      environment:
        GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
        GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      ports:
        - "3000:3000"
      volumes:
        - ./docker/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
        - ./docker/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
        - ./docker/grafana/DashboardTelegraf.json:/var/lib/grafana/dashboards/DashboardTelegraf.json
        - grafana-data:/var/lib/grafana


volumes:
    influxdb-data:
    grafana-data:
