{
 "title": "Ethplants Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "exchange_name",
    "label": "Exchange",
    "query": "SHOW TAG VALUES WITH KEY = \"exchange\""
   },
   {
    "name": "trading_pair",
    "label": "Trading Pair",
    "query": "SHOW TAG VALUES WITH KEY = \"trading_pair\" WHERE \"exchange\" =~ /^$exchange_name$/ "
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_miner_total_earnings",
     "select": [
      [
       { "params": [ "total_chart_earnings_usd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last 7d Rewards" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trade Fees -vs- Rewards",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "query": "SELECT moving_average(sum(\"total_flat_fee\"), 2) AS \"Hourly Trade Fees\" FROM \"hb_trades\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "total_pnl" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Total PNL" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" }
     ],
     "measurement": "hb_miner_earnings",
     "select": [
      [
       { "params": [ "summary_stats_usd_payout" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total Rewards" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Funds Usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "query": "SELECT mean(\"cur_value\") - mean(\"cur_quote_bal\") AS \"_Inventory\" FROM \"hb_strat_pnl_report\" WHERE (\"trading_pair\" =~ /^$trading_pair$/) AND $timeFilter GROUP BY time($__interval), \"trading_pair\" fill(null)",
     "select": [
      [
       { "params": [ "cur_quote_bal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "USDT Balance" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "bid_user_open_usd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_Open Buy" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "select": [
      [
       { "params": [ "cur_quote_bal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "USDT Inventory" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "hb_trades",
     "query": "SELECT cumulative_sum(\"total_flat_fee\") FROM \"hb_trades\" WHERE (\"trading_pair\" =~ /^$trading_pair$/) AND $timeFilter GROUP BY \"trading_pair\"",
     "select": [
      [
       { "params": [ "total_flat_fee" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Trade Fees" ], "type": "alias" }
      ]
     ]
    },
    {
     "measurement": "hb_miner_earnings",
     "select": [
      [
       { "params": [ "summary_stats_usd_payout" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Rewards" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Returns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "query": "SELECT cumulative_sum(\"total_flat_fee\") FROM \"hb_trades\" WHERE (\"trading_pair\" =~ /^$trading_pair$/) AND $timeFilter GROUP BY \"trading_pair\"",
     "select": [
      [
       { "params": [ "total_pnl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "PNL" ], "type": "alias" }
      ],
      [
       { "params": [ "cur_base_bal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_Base Balance" ], "type": "alias" }
      ],
      [
       { "params": [ "cur_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_Cur Price" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "hb_miner_snapshots",
     "query": "SELECT sum(\"ask_user_reward_usd\") *$__interval AS \"Total Rewards ASK\", sum(\"bid_user_reward_usd\") *$__interval AS \"Total Rewards BID\" FROM \"hb_miner_snapshots\" WHERE (\"trading_pair\" =~ /^$trading_pair$/) AND $timeFilter GROUP BY time($__interval), \"trading_pair\" fill(previous)",
     "select": [
      [
       { "params": [ "ask_user_reward_usd" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "Total Rewards ASK" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_user_reward_usd" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "Total Rewards BID" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "bid_user_open_usd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Open Buy" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Strategies",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 9, "x": 4, "y": 10 },
   "targets": [
    {
     "alias": "$tag_trading_pair",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "strategy_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rewards -vs- Trade fees",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_trading_pair",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "query": "SELECT cumulative_sum(\"total_flat_fee\") FROM \"hb_trades\" WHERE (\"trading_pair\" =~ /^$trading_pair$/) AND $timeFilter GROUP BY \"trading_pair\"",
     "select": [
      [
       { "params": [ "total_pnl" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "Total PNL" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy_status_tag", "operator": "=", "value": "trading" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "hb_miner_earnings",
     "select": [
      [
       { "params": [ "summary_stats_usd_payout" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "Total Rewards (Projected)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Snapshots Mean Age Latency Change per minute, last 30 minutes",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_exchange",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "exchange" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hb_miner_markets",
     "select": [
      [
       { "params": [ "data_age_at_collection_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       {
        "params": [
         30
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Funds Usage",
   "type": "status-history",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "$tag_trading_pair - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "query": "SELECT mean(\"cur_value\") - mean(\"cur_quote_bal\") AS \"Inventory\" FROM \"hb_strat_pnl_report\" WHERE (\"trading_pair\" =~ /^$trading_pair$/) AND $timeFilter GROUP BY time($__interval), \"trading_pair\" fill(null)",
     "select": [
      [
       { "params": [ "cur_quote_bal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "USDT Balance" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$tag_trading_pair - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "bid_user_open_usd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Open Buy" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "title": "Median Hummingbot Miner Snapshots Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_exchange/$col",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "exchange" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_miner_markets",
     "select": [
      [
       { "params": [ "data_age_at_collection_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Funds Usage",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "query": "SELECT mean(\"cur_value\") - mean(\"cur_quote_bal\") AS \"_Inventory\" FROM \"hb_strat_pnl_report\" WHERE (\"trading_pair\" =~ /^$trading_pair$/) AND $timeFilter GROUP BY time($__interval), \"trading_pair\" fill(null)",
     "select": [
      [
       { "params": [ "cur_quote_bal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "USDT Balance" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "bid_user_open_usd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_Open Buy" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "select": [
      [
       { "params": [ "cur_quote_bal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "USDT Inventory" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  { "title": "Market Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }, "repeat": "Filters" },
  {
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "exchange" ], "type": "tag" }
     ],
     "measurement": "hb_miner_snapshots",
     "select": [
      [
       { "params": [ "data_age_at_collection_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "USD Rewards per pair",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hb_miner_snapshots",
     "select": [
      [
       { "params": [ "user_reward" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "title": "Posted yield by trading pair",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_trading_pair",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_miner_snapshots",
     "select": [
      [
       { "params": [ "annualized_return" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=~", "value": "/^$exchange_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Latest Ask -vs- Eligible",
   "type": "table",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 56 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "trading_pair" ], "type": "tag" }
     ],
     "measurement": "hb_miner_earnings",
     "query": "SELECT sum(\"summary_stats_oov_eligible_ask\") AS \"Eligible Ask\", sum(\"summary_stats_oov_ask\") AS \"Total Ask\", sum(\"summary_stats_oov_eligible_bid\") AS \"Eligible Bid\", sum(\"summary_stats_oov_bid\") AS \"Total Bid\", sum(\"summary_stats_usd_payout\") AS \"Rewards\" FROM \"hb_miner_earnings\" WHERE $timeFilter GROUP BY \"trading_pair\"",
     "select": [
      [
       { "params": [ "summary_stats_oov_eligible_ask" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Eligible Ask" ], "type": "alias" }
      ],
      [
       { "params": [ "summary_stats_oov_ask" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total Ask" ], "type": "alias" }
      ],
      [
       { "params": [ "summary_stats_oov_eligible_bid" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Eligible Bid" ], "type": "alias" }
      ],
      [
       { "params": [ "summary_stats_oov_bid" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total Bid" ], "type": "alias" }
      ],
      [
       { "params": [ "summary_stats_usd_payout" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Rewards" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "trading_pair" ], "type": "tag" }
     ],
     "measurement": "hb_trades",
     "query": "SELECT \"total_flat_fee\" AS \"Trade Fees\", \"total_flat_fee\" AS \"Trades\" FROM \"hb_trades\" GROUP BY \"trading_pair\"",
     "select": [
      [
       { "params": [ "total_flat_fee" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Trade Fees" ], "type": "alias" }
      ],
      [
       { "params": [ "total_flat_fee" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Trades" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Performance $trading_pair", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }, "repeat": "trading_pair" },
  {
   "title": "Trade Prices",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "mid_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Mid Price" ], "type": "alias" }
      ],
      [
       { "params": [ "ask_itm_median_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ask Spread" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_itm_median_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bid Spread" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$tag_trade_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "trade_type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_trades",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "title": "Returns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col/$tag_trade_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "trade_type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "query": "SELECT cumulative_sum(\"total_flat_fee\") FROM \"hb_trades\" WHERE (\"trading_pair\" =~ /^$trading_pair$/) AND $timeFilter GROUP BY \"trading_pair\"",
     "select": [
      [
       { "params": [ "total_pnl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "PNL" ], "type": "alias" }
      ],
      [
       { "params": [ "cur_base_bal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_Base Balance" ], "type": "alias" }
      ],
      [
       { "params": [ "cur_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_Cur Price" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "hb_miner_snapshots",
     "query": "SELECT sum(\"ask_user_reward_usd\") *$__interval AS \"Total Rewards ASK\", sum(\"bid_user_reward_usd\") *$__interval AS \"Total Rewards BID\" FROM \"hb_miner_snapshots\" WHERE (\"trading_pair\" =~ /^$trading_pair$/) AND $timeFilter GROUP BY time($__interval), \"trading_pair\" fill(previous)",
     "select": [
      [
       { "params": [ "ask_user_reward_usd" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "Total Rewards ASK" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_user_reward_usd" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "Total Rewards BID" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "bid_user_open_usd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Open Buy" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "title": "Profit and Loss",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "select": [
      [
       { "params": [ "num_trades" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Trades" ], "type": "alias" }
      ],
      [
       { "params": [ "cur_base_bal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "_BaseBalance" ], "type": "alias" }
      ],
      [
       { "params": [ "cur_price" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "_Price" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "bid_user_open_usd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Open Buy" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "title": "Spreads ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "hb_miner_snapshots",
     "select": [
      [
       { "params": [ "bid_user_average_spread" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "_Bid Spread Rewards" ], "type": "alias" }
      ],
      [
       { "params": [ "ask_user_average_spread" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "_Ask Spread Rewards" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_average_spread" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "Market Bid Spread" ], "type": "alias" }
      ],
      [
       { "params": [ "ask_average_spread" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Market Ask Spread" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "ask_itm_median_spread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "Median Market Ask Spread (strat)"
        ],
        "type": "alias"
       }
      ],
      [
       { "params": [ "bid_itm_median_spread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       {
        "params": [
         "Median Market Bid Spread (strat)"
        ],
        "type": "alias"
       }
      ],
      [
       { "params": [ "market_max_spread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Max Spread" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_user_mean_spread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "_Bid Spread User" ], "type": "alias" }
      ],
      [
       { "params": [ "ask_user_mean_spread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_Ask Spread User" ], "type": "alias" }
      ],
      [
       { "params": [ "mid_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " * 100" ], "type": "math" },
       { "params": [ "_Mid Price Delta" ], "type": "alias" }
      ],
      [
       { "params": [ "mid_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_Mid Price" ], "type": "alias" }
      ],
      [
       { "params": [ "market_max_spread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "Max Spread" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "type": "status-history",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "select": [
      [
       { "params": [ "total_pnl" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Trading PNL" ], "type": "alias" }
      ],
      [
       { "params": [ "fee_in_quote" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "Trade Fees" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_miner_snapshots",
     "select": [
      [
       { "params": [ "user_reward" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Rewards" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "type": "status-history",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "bid_user_mean_spread" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bid Spread" ], "type": "alias" }
      ],
      [
       { "params": [ "optimal_spread" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Optimal Spread" ], "type": "alias" }
      ],
      [
       { "params": [ "ask_user_mean_spread" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ask Spread" ], "type": "alias" }
      ],
      [
       { "params": [ "volatility_indicator" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Volatility Indicator" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "title": "Captured Rewards Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_miner_snapshots",
     "select": [
      [
       { "params": [ "volume_usd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Posted Liquidity" ], "type": "alias" }
      ],
      [
       { "params": [ "ask_total_oov_eligible" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "_Ask Volume" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_total_oov_eligible" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "_Bid Volume" ], "type": "alias" }
      ],
      [
       { "params": [ "market_mid_price" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "_Price" ], "type": "alias" }
      ],
      [
       { "params": [ "ask_user_eligible_oov" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "_User Ask Volume" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_user_eligible_oov" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "_User Bid Volume" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "title": "Market Rewards Participation",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 85 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "2" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "market_max_spread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_MarketSpread" ], "type": "alias" }
      ],
      [
       { "params": [ "ask_user_mean_spread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_AskSpread" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_user_mean_spread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_BidSpread" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "title": "Yield",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "$col/$tag_trade_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "trade_type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_strat_pnl_report",
     "query": "SELECT cumulative_sum(\"total_flat_fee\") FROM \"hb_trades\" WHERE (\"trading_pair\" =~ /^$trading_pair$/) AND $timeFilter GROUP BY \"trading_pair\"",
     "select": [
      [
       { "params": [ "total_pnl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*24 *3600000 /$__interval_ms" ], "type": "math" },
       { "params": [ "PNL" ], "type": "alias" }
      ],
      [
       { "params": [ "cur_base_bal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_Base Balance" ], "type": "alias" }
      ],
      [
       { "params": [ "cur_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_Cur Price" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "hb_miner_snapshots",
     "query": "SELECT sum(\"ask_user_reward_usd\") *$__interval AS \"Total Rewards ASK\", sum(\"bid_user_reward_usd\") *$__interval AS \"Total Rewards BID\" FROM \"hb_miner_snapshots\" WHERE (\"trading_pair\" =~ /^$trading_pair$/) AND $timeFilter GROUP BY time($__interval), \"trading_pair\" fill(previous)",
     "select": [
      [
       { "params": [ "ask_user_reward_usd" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*24 *3600000 /$__interval_ms" ], "type": "math" },
       { "params": [ "Total Rewards ASK" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_user_reward_usd" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*24 *3600000 /$__interval_ms" ], "type": "math" },
       { "params": [ "Total Rewards BID" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "bid_user_open_usd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Open Buy" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "title": "Captured Rewards Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_miner_snapshots",
     "select": [
      [
       { "params": [ "user_volume_pct" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Eligible Volume Percent" ], "type": "alias" }
      ],
      [
       { "params": [ "user_reward_pct" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rewards Percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  },
  {
   "title": "USD Bid and Ask Pressure (ITM median)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "trading_pair" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hb_strat_heartbeat",
     "select": [
      [
       { "params": [ "ask_itm_liquidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ask Market Liquidity" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_itm_liquidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" },
       { "params": [ "Bid Market Liquidity" ], "type": "alias" }
      ],
      [
       { "params": [ "ask_user_open_orders_usd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ask User Open Liquidity" ], "type": "alias" }
      ],
      [
       { "params": [ "bid_user_open_orders_usd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "Bid User Open Liquidity" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "hb_miner_snapshots",
     "select": [
      [
       { "params": [ "bid_total_oov_eligible" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "_bid_volume" ], "type": "alias" }
      ],
      [
       { "params": [ "ask_total_oov_eligible" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_ask_volume" ], "type": "alias" }
      ],
      [
       { "params": [ "market_mid_price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "_mid_price" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "trading_pair", "operator": "=~", "value": "/^$trading_pair$/" }
     ]
    }
   ]
  }
 ]
}